"""
Data models for the signal loop.

Defines:
- Signal: Core trading signal with critic evaluation results
- SignalLogEntry: JSONL entry for signal logging
- AccuracyRecord: Record of signal accuracy verification
- Direction mapping utilities
"""

from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Literal

from loguru import logger


SignalDirection = Literal["LONG", "SHORT", "FLAT"]


@dataclass(slots=True)
class Signal:
    """
    Production trading signal with critic evaluation results.

    Generated by signal loop, evaluated by critic, optionally executed.
    """

    # Core signal fields
    symbol: str
    timeframe: str
    direction: SignalDirection
    confidence: float
    reasoning: str
    persona: str
    timestamp: datetime
    market_regime: str

    # Market context
    current_price: float = 0.0
    rsi: float = 50.0
    macd: float = 0.0
    macd_signal: float = 0.0
    bb_position: float = 0.5

    # Critic evaluation (filled after critique)
    critic_score: float | None = None
    critic_recommendation: str | None = None
    critic_override: bool = False
    critic_reasoning: str | None = None

    # Final decision
    final_direction: SignalDirection | None = None

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        data = asdict(self)
        data["timestamp"] = self.timestamp.isoformat()
        return data


@dataclass(slots=True, frozen=True)
class SignalLogEntry:
    """
    Entry for signal_log.jsonl.

    Captures complete signal lifecycle: generation, critique, execution decision.
    """

    timestamp: str  # ISO format
    symbol: str
    timeframe: str
    direction: str
    confidence: float
    persona: str
    market_regime: str
    reasoning: str
    current_price: float

    # Critic fields
    critic_score: float | None
    critic_recommendation: str | None
    critic_override: bool

    # Final outcome
    final_direction: str
    executed: bool
    trade_decision_reason: str | None

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)


@dataclass(slots=True, frozen=True)
class AccuracyRecord:
    """
    Record of signal accuracy verification.

    Created after waiting for next bar to close and comparing
    predicted direction to actual price movement.
    """

    signal_timestamp: str  # ISO format
    symbol: str
    timeframe: str
    predicted_direction: str
    actual_direction: str
    correct: bool
    signal_confidence: float
    entry_price: float
    exit_price: float
    actual_return_pct: float
    verified_at: str  # ISO format

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)


def map_generator_to_signal(direction: str) -> SignalDirection:
    """
    Map generator direction (HIGHER/LOWER) to execution signal (LONG/SHORT).

    Generator tasks produce:
    - PREDICT_DIRECTION: HIGHER / LOWER
    - ASSESS_MOMENTUM: INCREASING / DECREASING

    Execution layer uses:
    - LONG / SHORT / FLAT

    Args:
        direction: Generator direction string

    Returns:
        Mapped signal direction (FLAT if unmapped)
    """
    mapping = {
        "HIGHER": "LONG",
        "LOWER": "SHORT",
        "INCREASING": "LONG",
        "DECREASING": "SHORT",
    }

    result = mapping.get(direction.upper(), "FLAT")

    if result == "FLAT" and direction.upper() not in ("FLAT", "NEUTRAL"):
        logger.warning(
            "Unknown direction mapped to FLAT",
            original=direction,
        )

    return result


def get_timeframe_duration_ms(timeframe: str) -> int:
    """
    Get duration of a timeframe in milliseconds.

    Args:
        timeframe: Timeframe string (1m, 5m, 15m, 1h, 4h, 1d)

    Returns:
        Duration in milliseconds
    """
    durations = {
        "1m": 60_000,
        "5m": 300_000,
        "15m": 900_000,
        "1h": 3_600_000,
        "4h": 14_400_000,
        "1d": 86_400_000,
    }

    return durations.get(timeframe, 3_600_000)  # Default to 1h


def get_verification_horizon_bars(timeframe: str) -> int:
    """
    Get number of bars to wait before verifying accuracy.

    For simplicity, verify against next bar close (1 bar).

    Args:
        timeframe: Timeframe string

    Returns:
        Number of bars to wait
    """
    # Use 1 bar for all timeframes (next bar outcome)
    return 1
